export const TEXT = {
  EDIT: "Edit",
  BUSINESS_DETAILS: "Business Details",
  BUSINESS_NAME: "Business Name",
  BUSINESS_ADDRESS: "Address",
  OR: "Or",
  BUSINESS_INFO: "Select a Client/Business from the list",
  bussinessImage: {
    TITLE: "Add Business Logo",
    DESCRIPTION: "Resolution up to 1080x1080px.",
    TYPE: "PNG or JPEG file",
    REMOVE: "Remove",
    CHANGE: "Change",
  },
  signatureImage: {
    TITLE: "Signature",
    RESET: "Reset",
    BUTTON: "Upload Signature",
    DESCRIPTION: "Authorised Signatory",
  },
  quotation: {
    TITLE: "Quotation",
    QUOTATION_NO: "Quotation No",
    QUOTATION_DATE: "Quotation Date",
    VALID_TILL: "Valid Till Date",
    ADD_MORE_FIELDS: "Add More Fields",
  },
  BUSINESS: {
    FROM_SECTION: "Quotation From",
    DETAIL: "Your Details",
    BUTTON: "Add New Business",
    PLACEHOLDER: "Select a Business",
  },
  CLIENT: {
    TITLE: "Quotation For",
    DETAIL: "(Client's Details)",
    BUTTON: "Add New Client",
    PLACEHOLDER: "Select a Client",
  },
  ITEMS: {
    ITEM: "Item",
    HSN_SAC: "HSN/SAC",
    GST_RATE: "GST Rate",
    QUANTITY: "Quantity",
    RATE: "Rate",
    AMOUNT: "Amount",
    CGST: "CGST",
    SGST: "SGST",
    TOTAL: "Total",
  },
  TERMS_AND_CONDIITION: {
    TITLE: "Terms and Conditions",
    NEW_TERM: "Add New Term",
    NEW_GROUP: "Add New Group",
  },
  BUTTONS: {
    SAVE: "Save & Continue",
    ADD_ITEM: "Add New Line",
    DOWNLOAD_PDF: "Download PDF",
    ENABLE_GST: "Show GST",
    DISABLE_GST: "Hide GST",
    ADDITION_INFO: "Add Additional Info",
  },
};
